import { defaultCategories } from "./categories";
import { allocateSplits } from "./calculations";
import type { AppSnapshot, Expense } from "./types";

const now = "2026-08-10T17:00:00.000Z";

function expense(
  id: string,
  description: string,
  categoryId: string,
  payerId: string,
  amount: number,
  date: string,
  memberIds: string[],
): Expense {
  return {
    id,
    recordType: "expense",
    groupId: "group-family",
    eventId: "event-toronto",
    description,
    categoryId,
    transactionDate: date,
    payerId,
    amountOriginal: amount,
    currencyOriginal: "CAD",
    exchangeRate: 1,
    amountBase: amount,
    baseCurrency: "CAD",
    exchangeRateSource: "same-currency",
    createdBy: payerId,
    createdAt: date,
    updatedAt: date,
    version: 1,
    syncStatus: "synced",
    splits: allocateSplits(id, amount, "CAD", "equal", memberIds.map((memberId) => ({ memberId }))),
  };
}

export const seedSnapshot: AppSnapshot = {
  currentUser: { id: "user-tom", name: "Tom Moshi", email: "tom@example.com", defaultCurrency: "CAD" },
  groups: [
    {
      id: "group-family",
      name: "Moshi Family",
      emoji: "👨‍👩‍👧‍👦",
      description: "Trips, dinners, and activities with the family.",
      currency: "CAD",
      ownerId: "user-tom",
      createdAt: "2026-07-20T12:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "group-roommates",
      name: "Roommates",
      emoji: "🏠",
      description: "Shared home activities and outings.",
      currency: "CAD",
      ownerId: "user-tom",
      createdAt: "2026-07-25T12:00:00.000Z",
      updatedAt: now,
    },
  ],
  groupMembers: [
    { id: "group-member-tom-family", groupId: "group-family", userId: "user-tom", name: "Tom", email: "tom@example.com", role: "owner", status: "active", joinedAt: now, avatarColor: "#2F80ED" },
    { id: "group-member-alex-family", groupId: "group-family", userId: "user-alex", name: "Alex", email: "alex@example.com", role: "member", status: "active", joinedAt: now, avatarColor: "#9B51E0" },
    { id: "group-member-blair-family", groupId: "group-family", userId: "user-blair", name: "Blair", email: "blair@example.com", role: "member", status: "active", joinedAt: now, avatarColor: "#F2994A" },
    { id: "group-member-tom-roommates", groupId: "group-roommates", userId: "user-tom", name: "Tom", email: "tom@example.com", role: "owner", status: "active", joinedAt: now, avatarColor: "#2F80ED" },
  ],
  events: [
    {
      id: "event-toronto",
      groupId: "group-family",
      name: "2026 Toronto Trip",
      emoji: "🇨🇦",
      startDate: "2026-09-20",
      endDate: "2026-10-01",
      baseCurrency: "CAD",
      ownerId: "user-tom",
      createdAt: "2026-08-01T12:00:00.000Z",
      updatedAt: now,
      simplifyDebts: true,
    },
    {
      id: "event-japan",
      groupId: "group-family",
      name: "Japan 2027",
      emoji: "🇯🇵",
      startDate: "2027-04-03",
      endDate: "2027-04-16",
      baseCurrency: "JPY",
      ownerId: "user-tom",
      createdAt: "2026-08-05T12:00:00.000Z",
      updatedAt: "2026-08-09T12:00:00.000Z",
      simplifyDebts: true,
    },
  ],
  members: [
    { id: "member-tom", eventId: "event-toronto", userId: "user-tom", name: "Tom", email: "tom@example.com", role: "owner", status: "active", joinedAt: now, avatarColor: "#2F80ED" },
    { id: "member-alex", eventId: "event-toronto", userId: "user-alex", name: "Alex", email: "alex@example.com", role: "member", status: "active", joinedAt: now, avatarColor: "#9B51E0" },
    { id: "member-blair", eventId: "event-toronto", userId: "user-blair", name: "Blair", email: "blair@example.com", role: "member", status: "active", joinedAt: now, avatarColor: "#F2994A" },
    { id: "member-tom-jp", eventId: "event-japan", userId: "user-tom", name: "Tom", email: "tom@example.com", role: "owner", status: "active", joinedAt: now, avatarColor: "#2F80ED" },
    { id: "member-alex-jp", eventId: "event-japan", userId: "user-alex", name: "Alex", email: "alex@example.com", role: "member", status: "active", joinedAt: now, avatarColor: "#9B51E0" },
    { id: "member-blair-jp", eventId: "event-japan", userId: "user-blair", name: "Blair", email: "blair@example.com", role: "member", status: "active", joinedAt: now, avatarColor: "#F2994A" },
  ],
  categories: defaultCategories,
  expenses: [
    {
      id: "expense-personal-coffee",
      recordType: "expense",
      description: "Morning coffee",
      categoryId: "food",
      transactionDate: "2026-08-10T15:30:00.000Z",
      payerId: "user-tom",
      amountOriginal: 5.75,
      currencyOriginal: "CAD",
      exchangeRate: 1,
      amountBase: 5.75,
      baseCurrency: "CAD",
      exchangeRateSource: "same-currency",
      createdBy: "user-tom",
      createdAt: "2026-08-10T15:30:00.000Z",
      updatedAt: "2026-08-10T15:30:00.000Z",
      version: 1,
      syncStatus: "synced",
      splits: allocateSplits("expense-personal-coffee", 5.75, "CAD", "equal", [{ memberId: "user-tom" }]),
    },
    {
      id: "expense-groceries",
      recordType: "expense",
      groupId: "group-family",
      description: "Weekly groceries",
      categoryId: "groceries",
      transactionDate: "2026-08-09T18:00:00.000Z",
      payerId: "group-member-tom-family",
      amountOriginal: 96.3,
      currencyOriginal: "CAD",
      exchangeRate: 1,
      amountBase: 96.3,
      baseCurrency: "CAD",
      exchangeRateSource: "same-currency",
      createdBy: "user-tom",
      createdAt: "2026-08-09T18:00:00.000Z",
      updatedAt: "2026-08-09T18:00:00.000Z",
      version: 1,
      syncStatus: "synced",
      splits: allocateSplits(
        "expense-groceries",
        96.3,
        "CAD",
        "equal",
        ["group-member-tom-family", "group-member-alex-family", "group-member-blair-family"].map(
          (memberId) => ({ memberId }),
        ),
      ),
    },
    expense("expense-hotel", "Chelsea Hotel", "accommodation", "member-tom", 420, "2026-09-20T18:00:00.000Z", ["member-tom", "member-alex", "member-blair"]),
    expense("expense-rail", "VIA Rail", "public-transport", "member-alex", 85.2, "2026-09-21T13:30:00.000Z", ["member-tom", "member-alex", "member-blair"]),
    expense("expense-dinner", "Dinner at Pai", "food", "member-tom", 82.4, "2026-09-21T23:00:00.000Z", ["member-tom", "member-alex", "member-blair"]),
    expense("expense-uber", "Uber to CN Tower", "taxi", "member-blair", 26.12, "2026-09-22T15:10:00.000Z", ["member-tom", "member-alex", "member-blair"]),
  ],
  debtRecords: [],
  settlements: [],
  invitations: [
    {
      id: "invite-demo",
      groupId: "group-family",
      token: "TorontoDemo2026",
      createdBy: "user-tom",
      approvalRequired: true,
      defaultRole: "member",
      useCount: 0,
      isActive: true,
      createdAt: now,
    },
  ],
  joinRequests: [
    {
      id: "request-sam",
      invitationId: "invite-demo",
      groupId: "group-family",
      requesterUserId: "user-sam",
      requesterName: "Sam Lee",
      requesterEmail: "sam@example.com",
      status: "pending",
      requestedAt: "2026-08-10T16:15:00.000Z",
    },
  ],
  activity: [
    { id: "activity-1", groupId: "group-family", actorId: "user-sam", type: "join_requested", title: "Sam requested to join", detail: "Waiting for owner approval", createdAt: "2026-08-10T16:15:00.000Z" },
    { id: "activity-2", eventId: "event-toronto", actorId: "user-tom", type: "expense_created", title: "Dinner at Pai added", detail: "Tom paid CA$82.40", createdAt: "2026-09-21T23:00:00.000Z" },
  ],
};
